### PR TITLE
Change the CSS selector of the img element on the home page for trigg…

### PR DESCRIPTION
**Pull request by iceear**
…ering the bounce effect

### CODE REVIEW

**Comment by iceear** [comment]
@CrazyVulture I created a pull request for the code review, please poke around to get familiar with the tools and process.

**Comment by CrazyVulture** [comment]
damn it. the book says to put the 'img' element at the back of the class . Has the jquery selector style been changed these days?

**Comment by iceear** [comment]
No. It looks like the images are supposed to be added as child elements of #page-theme. The changes in the javascript just to make the bounce event being triggered, you might want to change the img position to follow what you’ve read in the book.

-Will

**Comment by CrazyVulture** [comment]
got it! guess i need more familiar with and use of jquery selectors...

**Pull request merged**
